name: civic_flutter
description: A Flutter app for curating infrastructure projects across Nigeria.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.0.0
  webview_flutter: ^4.0.7
  sqflite: ^2.3.3+1
  path: ^1.9.1
  logging: ^1.2.0
  flutter_dotenv: 5.0.2
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.3.0  
  mockito: ^5.4.4
  network_image_mock: ^2.1.1


flutter:
  uses-material-design: true
  assets:
    - .env      

dependency_overrides: 
  path: ^1.9.1
    
