name: CivicTrail CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
    
  #CI Job to build and test the application
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Flutter environment
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.7'
        channel: 'stable'
        cache: false
        
    - name: Flutter version check
      run: |
        flutter --version
        dart --version

    - name: Create .env for CI
      working-directory: civic_flutter
      run: |
        echo "API_URL=${{ secrets.API_URL }}" > .env
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env

    - name: Flutter pub get
      working-directory: civic_flutter
      run: |
        flutter pub get
    
    - name: Flutter analyze
      working-directory: civic_flutter
      run: flutter analyze

    - name: Flutter tests
      working-directory: civic_flutter
      run: |
        flutter test

    - name: Build Flutter APK
      working-directory: civic_flutter
      run: |
        flutter build apk --release

    - name: Upload Flutter APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: flutter-apk
        path: civic_flutter/build/app/outputs/flutter-apk/app-release.apk


      # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django checks
      run: |
        python manage.py check

    - name: Run tests
      run: |
        python manage.py test
        
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
            
  #CD job to deploy the application to Azure
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Log in to Azure using service principal credentials
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

        # Deploy to Azure Web App
      - name: Deploy Django to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'civictrail'
          package: .   